### ISSUE TITLE
Week 1 - Crossover Grading

### ISSUE THREAD

**Issue by florayuan18** [adhithin/lab-kit#11]
https://adhithin.github.io/lab-kit/

**Comment by risaiwazaki** [comment]
Outstanding project idea, great design plan, should have sub-requirements and more detailed plan of what each individual is working on instead of having vague requirements. Should address team goals as well rather than just individual goals. Overall project idea is going in the right direction!

**Comment by jm1021** [comment]
Nice Time Box.  With specific tasks detailed.  Has Overall Requirements.   Has something to link to and considering API.  No review of project owner meetings.

Team should at .9 to their individual scores this week.  .9/1 Team + n/4 indivdual.
